export const FETCH_ALL_TEE_TIMES_PENDING = "FETCH_ALL_TEE_TIMES_PENDING";
export const FETCH_ALL_TEE_TIMES_SUCCESS = "FETCH_ALL_TEE_TIMES_SUCCESS";
export const FETCH_ALL_TEE_TIMES_FAILED = "FETCH_ALL_TEE_TIMES_FAILED";

export const ADD_NEW_TEE_TIME_PENDING = "ADD_NEW_TEE_TIME_PENDING";
export const ADD_NEW_TEE_TIME_SUCCESS = "ADD_NEW_TEE_TIME_SUCCESS";
export const ADD_NEW_TEE_TIME_FAILED = "ADD_NEW_TEE_TIME_FAILED";

export const REMOVE_TEE_TIME_PENDING = "REMOVE_TEE_TIME_PENDING";
export const REMOVE_TEE_TIME_SUCCESS = "REMOVE_TEE_TIME_SUCCESS";
export const REMOVE_TEE_TIME_FAILED = "REMOVE_TEE_TIME_FAILED";

export const UPDATE_TEE_TIME_PENDING = "UPDATE_TEE_TIME_PENDING";
export const UPDATE_TEE_TIME_SUCCESS = "UPDATE_TEE_TIME_SUCCESS";
export const UPDATE_TEE_TIME_FAILED = "UPDATE_TEE_TIME_FAILED";
