export const FETCH_ALL_CUSTOMERS_TEE_TIMES_PENDING =
  "FETCH_ALL_CUSTOMERS_TEE_TIMES_PENDING";
export const FETCH_ALL_CUSTOMERS_TEE_TIMES_SUCCESS =
  "FETCH_ALL_CUSTOMERS_TEE_TIMES_SUCCESS";
export const FETCH_ALL_CUSTOMERS_TEE_TIMES_FAILED =
  "FETCH_ALL_CUSTOMERS_TEE_TIMES_FAILED";
